import { useEffect, useState } from "react";

function DataTables() {
  type User = {
    id: number;
    name: string;
    email: string;
    age: number;
    city: string;
    role: string;
    salary: number;
    status: "Active" | "Inactive";
  };

  const usersData: User[] = [
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
    {
      id: 1,
      name: "Rahul Sharma",
      email: "rahul@gmail.com",
      age: 24,
      city: "Surat",
      role: "Frontend Developer",
      salary: 35000,
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Patel",
      email: "priya@gmail.com",
      age: 26,
      city: "Ahmedabad",
      role: "Backend Developer",
      salary: 42000,
      status: "Active",
    },
    {
      id: 3,
      name: "Aman Verma",
      email: "aman@gmail.com",
      age: 23,
      city: "Mumbai",
      role: "UI Designer",
      salary: 30000,
      status: "Inactive",
    },
    {
      id: 4,
      name: "Neha Shah",
      email: "neha@gmail.com",
      age: 27,
      city: "Vadodara",
      role: "Full Stack Developer",
      salary: 55000,
      status: "Active",
    },
    {
      id: 5,
      name: "Rohan Mehta",
      email: "rohan@gmail.com",
      age: 29,
      city: "Pune",
      role: "Backend Developer",
      salary: 48000,
      status: "Active",
    },
    {
      id: 6,
      name: "Karan Joshi",
      email: "karan@gmail.com",
      age: 25,
      city: "Surat",
      role: "Frontend Developer",
      salary: 38000,
      status: "Inactive",
    },
    {
      id: 7,
      name: "Sneha Desai",
      email: "sneha@gmail.com",
      age: 28,
      city: "Ahmedabad",
      role: "HR Manager",
      salary: 45000,
      status: "Active",
    },
    {
      id: 8,
      name: "Vivek Singh",
      email: "vivek@gmail.com",
      age: 31,
      city: "Delhi",
      role: "Full Stack Developer",
      salary: 65000,
      status: "Active",
    },
    {
      id: 9,
      name: "Anjali Shah",
      email: "anjali@gmail.com",
      age: 24,
      city: "Mumbai",
      role: "Frontend Developer",
      salary: 36000,
      status: "Inactive",
    },
    {
      id: 10,
      name: "Arjun Patel",
      email: "arjun@gmail.com",
      age: 30,
      city: "Surat",
      role: "Backend Developer",
      salary: 52000,
      status: "Active",
    },
    {
      id: 11,
      name: "Mehul Joshi",
      email: "mehul@gmail.com",
      age: 26,
      city: "Rajkot",
      role: "UI Designer",
      salary: 32000,
      status: "Active",
    },
    {
      id: 12,
      name: "Pooja Mehta",
      email: "pooja@gmail.com",
      age: 25,
      city: "Pune",
      role: "Frontend Developer",
      salary: 40000,
      status: "Active",
    },
  ];

  const [showData, setShowData] = useState<User[]>([]);

  const pages = Array.from(
    { length: Math.ceil(usersData.length / 10) },
    (_, index) => 1 + index,
  );

  const [currentPage, setCurrentPage] = useState(1);

  const [searchQuery, setSearchQuery] = useState<string>("");

  const [sortValue, setSortValue] = useState<number | null>(null);

  useEffect(() => {
    const startIndex = (currentPage - 1) * 10;
    const endIndex = 10 * currentPage;
    const filterData: User[] = usersData.slice(startIndex, endIndex);

    setShowData(filterData);
  }, [currentPage]);

  useEffect(() => {
    if (searchQuery === "") {
      const startIndex = (currentPage - 1) * 10;
      const endIndex = 10 * currentPage;
      const filterData: User[] = usersData.slice(startIndex, endIndex);

      setShowData(filterData);
      return;
    }
    const filterDataBySearch = usersData.filter((value) =>
      [
        value.age,
        value.city,
        value.email,
        value.id,
        value.name,
        value.role,
        value.salary,
        value.status,
      ]
        .join(" ")
        .toLowerCase()
        .includes(searchQuery.trim().toLowerCase()),
    );

    setShowData(filterDataBySearch);
  }, [searchQuery]);

  useEffect(() => {
    if (!sortValue) {
      const startIndex = (currentPage - 1) * 10;
      const endIndex = 10 * currentPage;
      const filterData: User[] = usersData.slice(startIndex, endIndex);

      setShowData(filterData);
      return;
    }

    const filterDataBySearch = usersData.filter(
      (value) => value.salary >= sortValue,
    );

    setShowData(filterDataBySearch);
  }, [sortValue]);

  return (
    <>
      <div>
        <input
          type="text"
          value={searchQuery}
          className="w-100 h-10 rounded-2xl border-amber-500 border-4 mt-1"
          onChange={(e) => setSearchQuery(e.target.value)}
        />
        {
          <table>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Age</th>
              <th>City</th>
              <th>Role</th>
              <th>Salary</th>
              <th>Status</th>
            </tr>

            {showData.map((value, index) => (
              <tr key={`${value.id}-${index}`}>
                <td>{value.id}</td>
                <td>{value.name}</td>
                <td>{value.email}</td>
                <td>{value.age}</td>
                <td>{value.city}</td>
                <td>{value.role}</td>
                <td>{value.salary}</td>
                <td>{value.status}</td>
              </tr>
            ))}
          </table>
        }

        <div>
          <select onChange={(e) => setSortValue(e.target.value)}>
            <option value={""}>select None</option>
            <option value={40000}>Salary Above 40000</option>
            <option value={50000}>Salary Above 50000</option>
          </select>
        </div>
        <div className="flex gap-2 flex-wrap">
          {pages.map((value) => (
            <button
              className="w-5 h-6 bg-amber-200 text-center rounded"
              onClick={() => setCurrentPage(value)}
            >
              {value}
            </button>
          ))}
        </div>
      </div>
    </>
  );
}

export default DataTables;
